package org.geocuba.foresta.fajas.gui;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import org.geocuba.foresta.administracion_seguridad.VistaManager;
import org.geocuba.foresta.administracion_seguridad.db.JDBCAdapter;
import org.geocuba.foresta.administracion_seguridad.extensiones.ConnectionExt;
import org.geocuba.foresta.fajas.extensiones.AnchoCalculosExt;
import org.geocuba.foresta.fajas.writerTasks.Generar_Perfiles;
import org.geocuba.foresta.gestion_datos.FajaManager;
import org.geocuba.foresta.gestion_datos.Intensidad_lluviaManager;
import org.geocuba.foresta.herramientas.utiles.AlgUtils;
import org.geocuba.foresta.herramientas.utiles.Funciones_Utiles;
import org.geocuba.foresta.herramientas.utiles.gui.Panel;
import org.geocuba.foresta.herramientas.utiles.gui.UIUtils;
import org.gvsig.raster.grid.GridException;
import com.hardcode.gdbms.driver.exceptions.ReadDriverException;
import com.iver.andami.PluginServices;
import com.iver.cit.gvsig.exceptions.layers.LoadLayerException;
import com.iver.cit.gvsig.fmap.layers.FLayer;
import com.iver.cit.gvsig.fmap.layers.FLyrVect;

 /**
  *
  * @author Raisel
  */
 public class pAncho_Calculos extends Panel{

    /** Creates new form pAncho_Calculos */
    public pAncho_Calculos(String title, String length) {
        _length = length;
    	initComponents();
        _title = title;
        _panel_id = "_anchoCalc";//+_title;
        //_centered=true;
        jLLongitudRio.setText(_length);
       UIUtils.AddPanel(this);
       jTFDistPerfiles.requestFocusInWindow();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSeleccion = new javax.swing.ButtonGroup();
        bgLLuvia = new javax.swing.ButtonGroup();
        bgMetodo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFDistPerfiles = new javax.swing.JTextField();
        jLLongitudRio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRBHerreroMelch = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRBCurvasIFD = new javax.swing.JRadioButton();
        jLDuracion = new javax.swing.JLabel();
        jLProbabilidad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRBIntensidadLluvia = new javax.swing.JRadioButton();
        jTFIntensidadLluvia = new javax.swing.JTextField();
        jCBXDuracion = new javax.swing.JComboBox();
        jCBXProbabilidad = new javax.swing.JComboBox();
        jLVelocidadInfiltracion = new javax.swing.JLabel();
        jTFVelocidadInfiltracion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jRB3raParteLadera = new javax.swing.JRadioButton();
        jBGenPerfiles = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();

        bgLLuvia.add(jRBCurvasIFD);
        bgLLuvia.add(jRBIntensidadLluvia);

        bgMetodo.add(jRBHerreroMelch);
        bgMetodo.add(jRB3raParteLadera);

        setFocusCycleRoot(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Paso entre perfiles transectos (m) :");

        jTFDistPerfiles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFDistPerfiles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDistPerfilesKeyTyped(evt);
            }
        });

        jLLongitudRio.setText(_length);

        jLLongitudRio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLLongitudRio.setText("Longitud");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLLongitudRio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 319, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTFDistPerfiles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTFDistPerfiles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLLongitudRio)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Método"));

        jRBHerreroMelch.setText("Herrero - Melchanov");
        jRBHerreroMelch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHerreroMelchActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRBCurvasIFD.setSelected(true);
        jRBCurvasIFD.setText("Curvas Intensidad-Frecuencia-Duración");
        jRBCurvasIFD.setEnabled(false);
        jRBCurvasIFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCurvasIFDActionPerformed(evt);
            }
        });

        jLDuracion.setText("Duración del aguacero (min) :");
        jLDuracion.setEnabled(false);

        jLProbabilidad.setText("Probablilidad <tiempo de retorno> (%) :");
        jLProbabilidad.setEnabled(false);

        jRBIntensidadLluvia.setText("Intensidad de la lluvia (mm/min) :");
        jRBIntensidadLluvia.setEnabled(false);
        jRBIntensidadLluvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIntensidadLluviaActionPerformed(evt);
            }
        });

        jTFIntensidadLluvia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFIntensidadLluvia.setEnabled(false);
        jTFIntensidadLluvia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIntensidadLluviaKeyTyped(evt);
            }
        });

        jCBXDuracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBXDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jCBXDuracion.setEnabled(false);

        jCBXProbabilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBXProbabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jCBXProbabilidad.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRBCurvasIFD)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLProbabilidad)
                            .add(jLDuracion))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jCBXDuracion, 0, 67, Short.MAX_VALUE)
                            .add(jCBXProbabilidad, 0, 67, Short.MAX_VALUE))))
                .addContainerGap())
            .add(jPanel4Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jRBIntensidadLluvia)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTFIntensidadLluvia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRBCurvasIFD)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLDuracion)
                    .add(jCBXDuracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLProbabilidad)
                    .add(jCBXProbabilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRBIntensidadLluvia)
                    .add(jTFIntensidadLluvia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLVelocidadInfiltracion.setText("Velocidad de infiltración de los suelos de la faja (mm-min) :");
        jLVelocidadInfiltracion.setEnabled(false);

        jTFVelocidadInfiltracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFVelocidadInfiltracion.setEnabled(false);
        jTFVelocidadInfiltracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFVelocidadInfiltracionKeyTyped(evt);
            }
        });

        jRB3raParteLadera.setSelected(true);
        jRB3raParteLadera.setText("Tercera parte de la longitud de la ladera (L/3)");
        jRB3raParteLadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB3raParteLaderaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRBHerreroMelch)
                .addContainerGap(205, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRB3raParteLadera)
                .addContainerGap(85, Short.MAX_VALUE))
            .add(jPanel3Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTFVelocidadInfiltracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLVelocidadInfiltracion)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jRBHerreroMelch)
                .add(9, 9, 9)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8)
                .add(jLVelocidadInfiltracion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTFVelocidadInfiltracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRB3raParteLadera)
                .addContainerGap())
        );

        jBGenPerfiles.setText("Generar perfiles");
        jBGenPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenPerfilesActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBAceptar.setText("Crear faja");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jBGenPerfiles)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBCancelar)
                    .add(jBAceptar)
                    .add(jBGenPerfiles))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRB3raParteLaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB3raParteLaderaActionPerformed
     jRBCurvasIFD.setEnabled(false);
     jLDuracion.setEnabled(false);
     jCBXDuracion.setEnabled(false);
     jLProbabilidad.setEnabled(false);
     jCBXProbabilidad.setEnabled(false);
     jRBIntensidadLluvia.setEnabled(false);
     jTFIntensidadLluvia.setEnabled(false);
     jLVelocidadInfiltracion.setEnabled(false);
     jTFVelocidadInfiltracion.setEnabled(false);
    }//GEN-LAST:event_jRB3raParteLaderaActionPerformed

    private void jBGenPerfilesActionPerformed(java.awt.event.ActionEvent evt) 
    {
    	//if(jRB3raParteLadera.isSelected())
    	//{	
     	
     if(jTFDistPerfiles.getText().trim().length()>0)
     {
      double paso = Double.parseDouble(jTFDistPerfiles.getText());
      String longitud = jLLongitudRio.getText();
      longitud = longitud.substring(longitud.indexOf(':')+1, longitud.length());
      double longRio = Double.parseDouble(longitud);
      
	      if((longRio/paso) >= 2)
	      {	  
	         FLyrVect parteaguas = AnchoCalculosExt.parteaguas;  //(FLyrVect)AlgUtils.GetActiveView().getMapControl().getMapContext().getLayers().getLayer("Cuencas");
	         if(parteaguas != null)
	         {	 
	          FLayer perfiles = VistaManager.GetActiveView().getMapControl().getMapContext().getLayers().getLayer("Perfiles");
	          if(perfiles!=null)
	          {	  
	           if(!perfiles.isEditing()) //TODO OK !!!
	            PluginServices.cancelableBackgroundExecution(new Generar_Perfiles(paso, "Generando Perfiles...", AnchoCalculosExt.selectedLayer, parteaguas, true));
	           else
	        	JOptionPane.showMessageDialog(null, "No se pueden crear perfiles. "+"\n"+"La capa de 'Perfiles' no debe estar Editable", "Información", JOptionPane.WARNING_MESSAGE);   
	          }
	          else
	           PluginServices.cancelableBackgroundExecution(new Generar_Perfiles(paso, "Generando Perfiles...", AnchoCalculosExt.selectedLayer, parteaguas, true));
	         } 
	    	 else
	    	  JOptionPane.showMessageDialog(null, "No se obtuvo la capa 'Parteaguas'", "ERROR", JOptionPane.ERROR_MESSAGE);	  
	    	//}
	      }   
	      else
	       JOptionPane.showMessageDialog(null, "La razón entre la longitud del río y el paso entre los perfiles debe ser mayor o igual que 2. "+"\n"+
	    		   "Introduzca un valor correcto", "Información", JOptionPane.WARNING_MESSAGE);	  
     }
     else
   	  JOptionPane.showMessageDialog(null, "Debe introducir un paso entre perfiles", "ERROR", JOptionPane.ERROR_MESSAGE);
    	
    }                                             

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) 
    {
       if(jRB3raParteLadera.isSelected()) //Metodo de la 3ra parte de la longitud de la ladera
       {	   
    	FajaManager.Crear_Faja_TereceraParteLongitud();
    	Close();
       }
       else
       {
    	try {
    	    boolean flag = false;
    	    
    		if(jRBCurvasIFD.isSelected())
    		{
    		 if(!jCBXDuracion.getSelectedItem().toString().equals("") && !jCBXProbabilidad.getSelectedItem().toString().equals("") && !jTFVelocidadInfiltracion.getText().equals(""))
    		  flag = true;	 
    		}
    		else
    	    if(!jTFIntensidadLluvia.getText().equals("") && !jTFVelocidadInfiltracion.getText().equals(""))
    	     flag = true;	
    			
    		if(flag)
    		{ 	
    		 double Wf = Double.parseDouble(jTFVelocidadInfiltracion.getText());
    		 double Intensidad = 0;
    		 
    		 if(jRBCurvasIFD.isSelected())
    		 {
    		  double duracion = Double.parseDouble(jCBXDuracion.getSelectedItem().toString());
    		  double probabilidad = Double.parseDouble(jCBXProbabilidad.getSelectedItem().toString());
    		  
    		  double prec = Intensidad_lluviaManager.obtenerPrecipitación(probabilidad, duracion);
    		  
    		  Intensidad = prec/duracion;
    		 }
    		 else
    		  Intensidad = Double.parseDouble(jTFIntensidadLluvia.getText());	 
    		 
			 FajaManager.Aplicar_Herrero_Melchanov(Wf, Intensidad); //////////////////////////////////////////////
			 Close();
    		} 		
    		else
    		 JOptionPane.showMessageDialog(null, "Faltan datos por llenar", "Error", JOptionPane.ERROR_MESSAGE);	
			
		} catch (ReadDriverException e) {
			JOptionPane.showMessageDialog(null, "No se pudo obtener la capa vectorial");
			e.printStackTrace();
		} catch (LoadLayerException e) {
			e.printStackTrace();
		} catch (GridException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
       }	   
    }

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
       Close();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jRBCurvasIFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCurvasIFDActionPerformed
     //jLDuracion.setEnabled(!jRBIntensidadLluvia.isSelected());
     //jCBXDuracion.setEnabled(!jRBIntensidadLluvia.isSelected());
     jLProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());
     jCBXProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());

     jTFIntensidadLluvia.setEnabled(!jRBCurvasIFD.isSelected());
    }//GEN-LAST:event_jRBCurvasIFDActionPerformed

    private void jTFDistPerfilesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDistPerfilesKeyTyped
       char caracter = evt.getKeyChar();
       if(!Funciones_Utiles.formatoInputTextField(jTFDistPerfiles.getText(), caracter, 'D', 9))
        evt.consume();
    }//GEN-LAST:event_jTFDistPerfilesKeyTyped

    private void jTFIntensidadLluviaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIntensidadLluviaKeyTyped
       char caracter = evt.getKeyChar();
       if(!Funciones_Utiles.formatoInputTextField(jTFIntensidadLluvia.getText(), caracter, 'D', 9))
        evt.consume();
    }//GEN-LAST:event_jTFIntensidadLluviaKeyTyped

    private void jTFVelocidadInfiltracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFVelocidadInfiltracionKeyTyped
       char caracter = evt.getKeyChar();
       if(!Funciones_Utiles.formatoInputTextField(jTFVelocidadInfiltracion.getText(), caracter, 'D', 9))
        evt.consume();
    }//GEN-LAST:event_jTFVelocidadInfiltracionKeyTyped

    private void jRBHerreroMelchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHerreroMelchActionPerformed
     jRBCurvasIFD.setEnabled(true);

     jLDuracion.setEnabled(true);
     jCBXDuracion.setEnabled(true);
     jLProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());
     jCBXProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());

     jRBIntensidadLluvia.setEnabled(true);
     jTFIntensidadLluvia.setEnabled(!jRBCurvasIFD.isSelected());

     jLVelocidadInfiltracion.setEnabled(true);
     jTFVelocidadInfiltracion.setEnabled(true);
    }//GEN-LAST:event_jRBHerreroMelchActionPerformed

    private void jRBIntensidadLluviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIntensidadLluviaActionPerformed
    // jLDuracion.setEnabled(!jRBIntensidadLluvia.isSelected());
    // jCBXDuracion.setEnabled(!jRBIntensidadLluvia.isSelected());
     jLProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());
     jCBXProbabilidad.setEnabled(!jRBIntensidadLluvia.isSelected());

     jTFIntensidadLluvia.setEnabled(!jRBCurvasIFD.isSelected());
    }//GEN-LAST:event_jRBIntensidadLluviaActionPerformed

    public void enableAceptarButton()
    {
     jBAceptar.setEnabled(true);	
    }

    public JComboBox getComboDuracion(){
     return jCBXDuracion;
    }

    public JComboBox getComboProbabilidad(){
     return jCBXProbabilidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLLuvia;
    private javax.swing.ButtonGroup bgMetodo;
    private javax.swing.ButtonGroup bgSeleccion;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGenPerfiles;
    private javax.swing.JComboBox jCBXDuracion;
    private javax.swing.JComboBox jCBXProbabilidad;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLLongitudRio;
    private javax.swing.JLabel jLProbabilidad;
    private javax.swing.JLabel jLVelocidadInfiltracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRB3raParteLadera;
    private javax.swing.JRadioButton jRBCurvasIFD;
    private javax.swing.JRadioButton jRBHerreroMelch;
    private javax.swing.JRadioButton jRBIntensidadLluvia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFDistPerfiles;
    private javax.swing.JTextField jTFIntensidadLluvia;
    private javax.swing.JTextField jTFVelocidadInfiltracion;
    // End of variables declaration//GEN-END:variables
    private String _length = "";
}
