/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialogoUsuarios.java
 *
 * Created on 04-mar-2011, 22:15:42
 */

package org.geocuba.foresta.administracion_seguridad.gui;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import com.iver.andami.PluginServices;
import org.geocuba.foresta.herramientas.utiles.Funciones_Utiles;
import org.geocuba.foresta.herramientas.utiles.Global;
import org.geocuba.foresta.herramientas.utiles.gui.UIUtils;

/**
 *
 * @author Raisel
 */
public class ConfigurarConexionDlg extends javax.swing.JDialog {

    /** Creates new form dialogoUsuarios */
    public ConfigurarConexionDlg(java.awt.Frame parent, String title) {
        super(parent, true);
        initComponents();
        setTitle(title);
        setResizable(false);
        jTFUsuario.requestFocusInWindow();
        UIUtils.inhabilitaPegar(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFServidor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFPuerto = new javax.swing.JTextField();
        jTFUsuario = new javax.swing.JTextField();
        jTFBD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPFPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBAceptar.setIcon(new javax.swing.ImageIcon("D:"+Global.fileSeparator+"PROYECTOS"+Global.fileSeparator+"Tesis"+Global.fileSeparator+"gvSIG_1.11_FORESTA_WORKSPACE"+Global.fileSeparator+"extForesta"+Global.fileSeparator+"images"+Global.fileSeparator+"database_connect.png")); // NOI18N
        jBAceptar.setIcon(new javax.swing.ImageIcon(PluginServices.getPluginServices("org.geocuba.foresta").getPluginDirectory()+""+Global.fileSeparator+"images"+Global.fileSeparator+"database_connect.png"));
        jBAceptar.setText("Conectar");
        jBAceptar.setEnabled(false);

        jBCancelar.setIcon(new javax.swing.ImageIcon("D:"+Global.fileSeparator+"PROYECTOS"+Global.fileSeparator+"Tesis"+Global.fileSeparator+"gvSIG_1.11_FORESTA_WORKSPACE"+Global.fileSeparator+"extForesta"+Global.fileSeparator+"images"+Global.fileSeparator+"cancelar.png")); // NOI18N
        jBCancelar.setIcon(new javax.swing.ImageIcon(PluginServices.getPluginServices("org.geocuba.foresta").getPluginDirectory()+""+Global.fileSeparator+"images"+Global.fileSeparator+"cancelar.png"));
        jBCancelar.setText("Cerrar");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("URL del servidor");

        jLabel3.setText("Nombre de la base de datos");

        jTFServidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFServidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFServidorKeyTyped(evt);
            }
        });

        jLabel5.setText("Puerto de conexión");

        jTFPuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPuertoKeyTyped(evt);
            }
        });

        jTFUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyTyped(evt);
            }
        });

        jTFBD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jTFBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBDKeyTyped(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jPFPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jPFPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFPasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jTFPuerto)
                            .addComponent(jTFBD)
                            .addComponent(jPFPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFServidor)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUsuarioKeyTyped
     char caracter = evt.getKeyChar();
      if(!Funciones_Utiles.formatoInputTextField(jTFUsuario.getText(), caracter, 'N', 28))
       evt.consume();
    }//GEN-LAST:event_jTFUsuarioKeyTyped

    private void jPFPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFPasswordKeyTyped
      char caracter = evt.getKeyChar();
      if(!Funciones_Utiles.formatoInputTextField(jPFPassword.getText(), caracter, 'N', 29))
       evt.consume();
    }//GEN-LAST:event_jPFPasswordKeyTyped

    private void jTFServidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFServidorKeyTyped
      char caracter = evt.getKeyChar();
      if(!Funciones_Utiles.formatoInputTextField(jTFServidor.getText(), caracter, 'N', 20))
       evt.consume();
    }//GEN-LAST:event_jTFServidorKeyTyped

    private void jTFBDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBDKeyTyped
      char caracter = evt.getKeyChar();
      if(!Funciones_Utiles.formatoInputTextField(jTFBD.getText(), caracter, 'N', 15))
       evt.consume();
    }//GEN-LAST:event_jTFBDKeyTyped

    private void jTFPuertoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPuertoKeyTyped
     char caracter = evt.getKeyChar();
      if(!Funciones_Utiles.formatoInputTextField(jTFPuerto.getText(), caracter, 'I', 4))
       evt.consume();
    }//GEN-LAST:event_jTFPuertoKeyTyped

public JTextField getFieldUsuario(){
 return jTFUsuario;
}

public JPasswordField getFieldPassword(){
 return jPFPassword;
}

public JTextField getFieldServidor(){
 return jTFServidor;
}

public JTextField getFieldBD(){
 return jTFBD;
}

public JTextField getFieldPuerto(){
 return jTFPuerto;
}

public JButton getButtonAceptar(){
 return jBAceptar;
}

public JButton getButtonCancelar(){
 return jBCancelar;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFBD;
    private javax.swing.JTextField jTFPuerto;
    private javax.swing.JTextField jTFServidor;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables

}
